#!/bin/bash

#,s=16M,i=2M,o=200
function runmain {
    OCAMLRUNPARAM="l=100M,s=16M,i=2M,o=200" ./nativerepl.native $* ;
};

pushd . >/dev/null
cd `dirname $0`
if [ ! -e nativerepl.native ]; then
    echo "Please run 'make' first."
    exit 0
fi
runmain $*
popd >/dev/null

