#!/bin/bash

opam install batteries oclock camomile pa_monad_custom

for i in xtype; do
    cd ocamlsyntax/$i
    make
    make install || (make uninstall; make install)
    make clean
    cd ../../
done

ocamlbuild -clean
