version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:ubuntu-16.04_ocaml-4.04.2
    environment:
      - TERM: "xterm"
    steps:
      - checkout

      # - restore_cache: &restore-cache
      #     keys:
      #       - v1-opam-4.04.2-{{ .Branch }}-{{ checksum "opam/opam" }}
      #       - v1-opam-4.04.2-{{ .Branch }}
      #       - v1-opam-4.04.2

      - run: &check-source-hash
          name: Check if source hash needs update
          command: ./scripts/source-hash.sh check-if-updated

      - run: &compile
          name: Install dependencies and compile Makam
          command: opam pin add --yes .

      - run: &install-node
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt-get install -y nodejs
            mkdir ~/.config
            sudo npm install -g yarn

      # - save_cache:
      #     key: v1-opam-4.04.2-{{ .Branch }}-{{ checksum "opam/opam" }}
      #     paths: ~/.opam

      - run: &tests
          name: Run Tests
          command: opam config exec make makam-timing-tests

      - run: &npm-login
          name: Login to NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run: &npm-test-publish
          name: Publish test version to npm
          command: opam config exec make npm-test-publish

      - run: &compile-js
          name: Compile Makam.js
          command: opam config exec make js

      - run: &tests-js
          name: Run Tests for Makam.js
          command: |
            if [[ $(git log --format=oneline -n 1 $CIRCLE_SHA1) == *"[ci-test-js]"* ]]; then make makam-js-tests; fi

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
