version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:ubuntu-16.04_ocaml-4.04.2
    environment:
      - TERM: "xterm"
    steps:
      - checkout

      - run: &check-version-update
          name: Check if version update is needed
          command: ./scripts/makam-version.sh check-if-updated

      - run: &install-dependencies
          name: Install dependencies
          command: |
            opam pin add --yes makam . --no-action
            opam install --yes makam --deps-only

      - run: &compile
          name: Compile Makam
          command: opam config exec make

      - run: &install-node
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g yarn
            sudo chown -R $(whoami):$(id -gn $(whoami)) ~/.config

      - run: &npm-login
          name: Login to NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run: &compile
          name: Compile Makam
          command: opam config exec make

      - run: &prepare-npm-package
          name: Prepare npm package and install it
          command: |
            opam config exec make prepare-npm-package
            npm install makam-$(./scripts/makam-version.sh).tgz

      - run: &tests
          name: Run Tests
          command: make MAKAM=./node_modules/.bin/makam makam-timing-tests

      - run: &compile-js
          name: Compile Makam.js
          command: opam config exec make js

      - run: &tests-js
          name: Run Tests for Makam.js
          command: |
            if [[ $(git log --format=oneline -n 1 $CIRCLE_SHA1) == *"[ci-test-js]"* ]]; then make makam-js-tests; fi

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
