version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:ubuntu-16.04_ocaml-4.04.2
    environment:
      - TERM: "xterm"
    steps:
      - checkout

      - restore_cache: &restore-cache
          keys:
            - v1-opam-4.04.2-{{ .Branch }}-{{ checksum "opam/opam" }}
            - v1-opam-4.04.2-{{ .Branch }}
            - v1-opam-4.04.2

      - run: &compile
          name: Install dependencies and compile Makam
          command: opam pin add --yes . && opam upgrade makam

      - save_cache:
          key: v1-opam-4.04.2-{{ .Branch }}-{{ checksum "opam/opam" }}
          paths: ~/.opam

      - run: &tests
          name: Run Tests
          command: opam config exec make makam-tests

      - run: &compile-js
          name: Compile Makam.js
          command: opam config exec make js

      - run: &tests-js
          name: Run Tests for Makam.js
          command: |
            curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
            sudo apt-get install -y nodejs
            echo '%use "stdlib/parsing/tests". run_tests X ?' | node js/ | tee output | grep SUCCESSFUL
            cat output

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
