version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:ubuntu-16.04_ocaml-4.04.2
    environment:
      - TERM: "xterm"
    steps:
      - checkout

      - run:
          name: Check if build should be skipped on CircleCI only
          command: |
            if [[ $(git log --format=oneline -n 1 $CIRCLE_SHA1) == *"[circle-skip]"* ]]; then echo 1 > skip; fi
      
      - run: &check-version-update
          name: Check if version update is needed
          command: |
            [[ -e skip ]] || ./scripts/makam-version.sh check-if-updated

      - run: &install-dependencies
          name: Install dependencies
          command: |
            [[ -e skip ]] || opam pin add --yes makam . --no-action
            [[ -e skip ]] || opam install --yes makam --deps-only

      - run: &install-node
          name: Install Node.js
          command: |
            [[ -e skip ]] || curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            [[ -e skip ]] || sudo apt-get install -y nodejs
            [[ -e skip ]] || sudo npm install -g yarn
            [[ -e skip ]] || sudo chown -R $(whoami):$(id -gn $(whoami)) ~/.config

      - run: &npm-login
          name: Login to NPM
          command: |
            [[ -e skip ]] || echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run: &compile
          name: Compile Makam
          command: |
            [[ -e skip ]] || opam config exec make

      - run: &prepare-npm-package
          name: Prepare npm package and install it
          command: |
            [[ -e skip ]] || opam config exec make prepare-test-npm-package
            [[ -e skip ]] || npm install makam-$(./scripts/makam-version.sh npm-test-version).tgz

      - run: &tests
          name: Run Tests
          command: |
            [[ -e skip ]] || make MAKAM=./node_modules/.bin/makam makam-timing-tests

      - run: &compile-js
          name: Compile Makam.js
          command: |
            [[ -e skip ]] || opam config exec make js

      - run: &tests-js
          name: Run Tests for Makam.js
          command: |
            [[ -e skip ]] || if [[ $(git log --format=oneline -n 1 $CIRCLE_SHA1) == *"[ci-test-js]"* ]]; then make makam-js-tests; fi

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
